micronaut:
  application:
    name: generic-graphql-api
  server:
    port: ${PORT:8080}
    host: 0.0.0.0  # Important for Docker containers
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:pleaseChangeThisSecretForProduction}

mongodb:
  uri: ${MONGODB_URI:mongodb://mongodb:27017/generic-graphql-api}

graphql:
  enabled: ${GRAPHQL_ENABLED:true}
  path: /graphql
  graphiql:
    enabled: ${GRAPHIQL_ENABLED:true}
    path: /graphiql

endpoints:
  health:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

logger:
  levels:
    lokinious.graphql_api: ${LOG_LEVEL:INFO}
    root: WARN
